[package]
name = "creator"
version = "0.1.0"
edition = "2021"

[lib]
name = "creator"
path = "src/lib.rs"

[[bin]]
name = "creator"
path = "src/main.rs"

[dependencies]
os_info = "3.7.0"
slint = "1.3.2"
#gtk4 = "0.7.3"
